### ISSUE TITLE
Web scan error

### ISSUE THREAD

**Issue by alirazmkhah** [danieljampen/multiav#2]
I pulled and installed multiav,
The multiav updates successfully in web interface!
 But uploading and scanning file has no result!

configs modified and set addresses for network to 127.0.0.1 as local network, both docker and web interface are in the same machine!

would you help me?

**Comment by jampe** [comment]
The network addresses specified in config.cfg are used to create new docker networks (one with internet, and one without) which will be assigned to the av containers. Specifying 127.0.0.1 won't work there. Try restoring the default settings there, delete the created docker networks (if they exist) and restart multiav. The default configs are:

```
DOCKER_NETWORK_NO_INTERNET=10.192.212.0/24
DOCKER_NETWORK_NO_INTERNET_NAME=multiav-no-internet-bridge
DOCKER_NETWORK_INTERNET=10.168.137.0/24
DOCKER_NETWORK_INTERNET_NAME=multiav-internet-bridge
```

To delete the created docker networks, execute the following:

```
sudo docker network rm multiav-internet-bridge
sudo docker network rm multiav-no-internet-bridge
```

**Comment by jampe** [comment]
closed due to inactivity. Please reopen the issue if the problem still exists.
