### ISSUE TITLE
Internet policy doesn't match

### ISSUE THREAD

**Issue by fareedfauzi** [danieljampen/multiav#3]
Getting this after enable ENABLE_INTERNET_ACCESS

```
webapi: starting insert
webapi: insert complete
[FileInfo] Skipping. Internet policy doesn't match
[Sophos] Skipping. Internet policy doesn't match
[Avg] Skipping. Internet policy doesn't match
[ClamAV] Skipping. Internet policy doesn't match
[Comodo] Skipping. Internet policy doesn't match
[DrWeb] Skipping. Internet policy doesn't match
[EScan] Skipping. Internet policy doesn't match
[FProt] Skipping. Internet policy doesn't match
[FSecure] Skipping. Internet policy doesn't match
[McAfee] Skipping. Internet policy doesn't match
[Yara] Skipping. Internet policy doesn't match
[ShadowServer] Skipping. Internet policy doesn't match
[VirusTotal] Skipping. Internet policy doesn't match
webapi: scanning file of report 24 with engine NSRL...!
[PEScan] Skipping. Internet policy doesn't match
[Floss] Skipping. Internet policy doesn't match
```

The result in web interface for wannacry and cryptolocker due to the scanning skip

![image](https://user-images.githubusercontent.com/56353946/84865766-52024c80-b0ab-11ea-83b0-36e848d1dc9c.png)

Can you help me find the solution other than disable the ENABLE_INTERNET_ACCESS
@jampe

**Comment by jampe** [comment]
This error happens when you try to use an av which requires internet access (configurable via the config.cfg file in the multiav directory). There should be no need to enable internet for the av's which don't have this option enabled per default (See [here](https://github.com/jampe/MultiAV-Extended/blob/master/multiav/config.cfg)). So if you set ENABLE_INTERNET_ACCESS to 1 for those scanners and don't enable "Allow data leak to vendors" in the scan gui, this error occurs. 

Back to your question, if you want the av's to have internet and you've enabled the previously mentioned setting in the config, you've to enable the "allow data leak to vendors" flag on the scan GUI or API for it to work. This was implemented this way to prevent accidental leaks to the vendors.

cheers

**Comment by fareedfauzi** [comment]
Thanks a lot @jampe 💯 . It works now.

Picture 1
![image](https://user-images.githubusercontent.com/56353946/85380724-d94e3500-b56f-11ea-8149-c804c8ae6c1c.png)

Picture 2
![image](https://user-images.githubusercontent.com/56353946/85383730-e7518500-b572-11ea-9641-7cc5e74b7c42.png)


I have another questions. 

**Question 1**

In above result, I'm not sure why AVG sometimes give error result like that (Picture 1) and sometimes the result is works (Picture 2). Both are the same sample. Did you know why the result of AVG like in above screenshot? (Ignore Avast result. It may due to license).

**Question 2**

I'm getting this errors for all intel plugins. Do you have any ideas for this error?

```
[ShadowServer] Container: multiav-shadowserver-0e52f672-b530-11ea-b2e7-000c293b2f62 Exception in scan method: Expecting value: line 2 column 1 (char 1)

[ShadowServer] Scan failed. Error: Expecting value: line 2 column 1 (char 1)
```
```
[VirusTotal] Container: multiav-virustotal-0ef795ba-b530-11ea-b2e7-000c293b2f62 Exception in scan method: Expecting value: line 2 column 1 (char 1)

[VirusTotal] Scan failed. Error: Expecting value: line 2 column 1 (char 1)
```
```
[NSRL] Container: multiav-nsrl-0f2f2a70-b530-11ea-b2e7-000c293b2f62 Exception in scan method: Expecting value: line 2 column 1 (char 1)

[NSRL] Scan failed. Error: Expecting value: line 2 column 1 (char 1)
```

Zero result

![image](https://user-images.githubusercontent.com/56353946/85385025-63989800-b574-11ea-9b1c-a78777182481.png)

**Comment by jampe** [comment]
**Question 1**

This looks like an error in the avg container plugin by malice. I did fix a bug in this plugin already, it looks like there are more. Can you report the issue to them in their repository?

**Question 2**

Thanks for reporting this. I fixed it in the last commit, the intel plugins should work now. I noticed that the shadowserver plugin isn't working anymore (again, is maintained by the malice team, not me). Additionally, you need an API key for virustotal to work. I did update the readme accordingly.

**Comment by fareedfauzi** [comment]
Question 1
All right. I will open the issue. 

Question 2
Wow, thanks a lot Jampe. Ok noted!
